name: Liquibase Manual CI/CD

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Liquibase Action (update, rollback, status)'
        required: true
        default: 'update'
      rollbackTag:
        description: 'Tag name for rollback (required if action=rollback)'
        required: false

jobs:
  liquibase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download Liquibase CLI
        run: |
          curl -Lo liquibase.zip https://github.com/liquibase/liquibase/releases/download/v4.28.0/liquibase-4.28.0.zip
          unzip liquibase.zip -d liquibase-dist
          sudo mv liquibase-dist /usr/local/liquibase
          sudo ln -sf /usr/local/liquibase/liquibase /usr/local/bin/liquibase

      - name: Verify Liquibase installation (Safe)
        run: |
          if [ -f liquibase.properties ]; then mv liquibase.properties liquibase.properties.bak; fi
          liquibase --version
          if [ -f liquibase.properties.bak ]; then mv liquibase.properties.bak liquibase.properties; fi

      - name: Run Liquibase Action
        env:
          DB_USERNAME: ${{ secrets.LIQUIBASE_USERNAME }}
          DB_PASSWORD: ${{ secrets.LIQUIBASE_PASSWORD }}
          DB_URL: ${{ secrets.LIQUIBASE_URL }}
          ACTION: ${{ github.event.inputs.action }}
          ROLLBACK_TAG: ${{ github.event.inputs.rollbackTag }}
        run: |
          echo "changeLogFile=changelogs/master-changelog.xml" > liquibase-ci.properties
          echo "url=$DB_URL" >> liquibase-ci.properties
          echo "username=$DB_USERNAME" >> liquibase-ci.properties
          echo "password=$DB_PASSWORD" >> liquibase-ci.properties
          echo "driver=com.microsoft.sqlserver.jdbc.SQLServerDriver" >> liquibase-ci.properties
          echo "classpath=drivers/mssql-jdbc-12.10.1.jre11.jar" >> liquibase-ci.properties

          if [ ! -f drivers/mssql-jdbc-12.10.1.jre11.jar ]; then
            echo "❌ Missing JDBC driver: drivers/mssql-jdbc-12.10.1.jre11.jar"
            exit 1
          fi

          if [ "$ACTION" = "update" ]; then
            liquibase --defaultsFile=liquibase-ci.properties --log-level=debug update
          elif [ "$ACTION" = "status" ]; then
            liquibase --defaultsFile=liquibase-ci.properties --log-level=debug status
          elif [ "$ACTION" = "rollback" ]; then
            if [ -z "$ROLLBACK_TAG" ]; then
              echo "Rollback tag is required for rollback action"
              exit 1
            fi
            liquibase --defaultsFile=liquibase-ci.properties --log-level=debug rollback "$ROLLBACK_TAG"
          else
            echo "Unknown action: $ACTION"
            exit 1
          fi
